### ISSUE TITLE
DaloRadius with multiple Radius servers

### ISSUE THREAD

**Issue by ianfra** [lirantal/daloradius-web#1]
Hello Liran.  Thank you for DaloRadius.  It has been very useful for us.

I'm trying to figure out how to adapt it to check user online status on multiple Radius Authentication servers. 

I know that it can individually manage many different servers via the Config Locations Directive but my challenge is that the user may be authenticated by any one of my 4 Radius servers, so when I do a lookup at the Session Info Tab on mng-edit.php they may show as offline if the server they are authenticated by is not the one I am currently Managing.

I'm hoping to make a dashboard for the helpdesk that shows all the users online/offline status at a glance, using the checkUserOnline function, but I'm at a loss as to how to make it work across multiple auth servers.

Do you have a recommendation on how/where to efficiently check the radacct table on the other auth servers in order to accurately determine if they are actually online ?

Thanks,
Ian

**Comment by lirantal** [comment]
Hey @ianfra,

Thanks for your kind words.

You've clearly stated the proper use of the config locations directive so sounds like you have a great control of the setup and I'm happy to hear you're using it to its full extent.

I have an idea on how to solve the online status check but it requires a bit of dev work.
Since you have multiple instances of the database you can't just query all of them easily in one unified view. 

## Case 1 - If you only need to query for a specific user's online/offline status
create a small web page that given a username will call an API, the API end-point will connect to each of the databases and check if the user is online/offline and will report back if it found it online in any of them.

This one is a quick one off but not very scalable if you will add more and more db instances etc.

## Case 2 - You want to browse a list of online users at any given time across all db instances
What I'd suggest is that you have a dedicated helpdesk dashboard which is basically its own little app (doesn't need to be anything fancy) where you maintain a list of online users only - it queries its own database to pull the online users.

How do users get to this new app's database? In the FR setup for each of the db instances you need customize it so that upon successful auth (I think its referred to as `postauth` in FR life-cycle) you can execute a command, so you fire off an API call to your app with curl, where you pass-in the username and any other details you want to have that FR will give you on the connection context, and the app's API will insert it to this new app's database.

So it doesn't matter from which db instance the user came in, you'll always get a ping to another app of this new connection made. You should also fire off a similar web API call upon user logged off or you'd end up with a stale user listing in the new app's database.


Hope this helps.
We can think of more options too.

**Comment by ianfra** [comment]
Hello @lirantal 

I should mention that this is a Fixed Wireless environment.  The Auth servers are geographically separated with 1 at each of the fiber POP's.  4 in total.  Also that I am Much more of a Perl than a PHP guy so my ideas may be a bit whacky.

As you say I don't think that Case 1 would Scale too well. 

I do like the idea of Case 2, a radpostpostauth trigger, and had not considered that at all.  I would still need to poll in some way for users that dropped off though (?)  Although running queries on the syslog servers to look for a the log off event would work.  Actually I could do both log off and logon via syslog and use the CURL Idea to populate a dash board.

I was thinking about adding more directives to the daloradius.conf,php to query additional Auth  servers 
 checking each one for RADACCT start/stop/NULL status per user to determine the user online/offline status.   Modifying opendb and closedb to accommodate multiple $dbConnectString and $dbSocket  using an array for $dbSocket['SERVERNAME'] or some such, and adding onto the Fetch portion in the checkUserOnline function, with either an IF or a switch, to find the newest record across the servers.  Although maybe a Join would work there - I haven't done a table join across servers before - not sure what the performance of that would be given the latency between them.

So a couple of options.  I need to work out the pros and cons for our setup.

Thank you for taking the time to reply... if you have more feed back I would appreciate hearing it.

Cheers,
Ian

**Comment by lirantal** [comment]
Happy to help!
Sounds like you have it covered Ian ;-)

Goodluck and have fun!
